### ISSUE TITLE
Search bar does not render on 1.2.0 (requires revert to 1.1.7)

### ISSUE THREAD

**Issue by m0un10** [backstage/mkdocs-techdocs-core#124]
I noticed for docs built using `mkdocs` the search bar does not appear and these errors appear in the console

```
reportUnhandledError.ts:21 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at index.ts:100:26
    at map.ts:58:33
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at mergeInternals.ts:85:24
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at e._subscribe (innerFrom.ts:78:18)
    at e._trySubscribe (Observable.ts:244:19)
    at Observable.ts:234:18
main.js:106 Uncaught ReferenceError: base_url is not defined
    at main.js:106:41
```

To workaround this and be able to use search again, I simply downgraded to the previous version

`pip3 install mkdocs-techdocs-core==1.1.7`

I suspect the issue is `mkdocs-material-9.1.3`. When reverting the `techdocs-core` plugin it causes it to uses `mkdocs-material-8.1.11` and that works fine.

**Comment by robertmarsal** [comment]
Unfortunately this is still an issue

**Comment by malthe** [comment]
This is still a problem today.

My `pip freeze` output:
```
babel==2.18.0
backrefs==6.2
certifi==2026.2.25
charset-normalizer==3.4.6
click==8.3.1
colorama==0.4.6
ghp-import==2.1.0
idna==3.11
Jinja2==3.1.6
Markdown==3.10.2
markdown_graphviz_inline==1.1.3
MarkupSafe==3.0.3
mdx-truly-sane-lists==1.3
mergedeep==1.3.4
mkdocs==1.6.1
mkdocs-get-deps==0.2.2
mkdocs-material==9.7.1
mkdocs-material-extensions==1.3.1
mkdocs-monorepo-plugin==1.1.2
mkdocs-redirects==1.2.2
mkdocs-techdocs-core==1.6.1
packaging==26.0
paginate==0.5.7
pathspec==1.0.4
plantuml-markdown==3.11.1
platformdirs==4.9.4
Pygments==2.19.2
pymdown-extensions==10.19.1
python-dateutil==2.9.0.post0
python-slugify==8.0.4
PyYAML==6.0.3
pyyaml_env_tag==1.1
requests==2.32.5
six==1.17.0
text-unidecode==1.3
urllib3==2.6.3
watchdog==6.0.0
```
